"""
A complete website written entirely in Python — a single file.
No .html templates, no .css files. All markup and styling are
generated by Python functions.

Now includes a voice-call feature: two people can open /call,
type the same room code, and talk to each other using their
browser's microphone (WebRTC), with Flask-SocketIO handling the
"introduction" between the two browsers.

Run with:
    pip install flask flask-socketio
    python website.py

Then open http://localhost:5000

To test the call feature, open http://localhost:5000/call in TWO
separate browser windows (or two different devices), type the
SAME room code in both, and click "Join Call" on each.
"""

from flask import Flask, request, redirect, url_for, session
from flask_socketio import SocketIO, emit, join_room, leave_room
from werkzeug.security import generate_password_hash, check_password_hash
from functools import wraps
import sqlite3
import html as html_lib

app = Flask(__name__)
app.config["SECRET_KEY"] = "dev-secret-key-change-this"
socketio = SocketIO(app, cors_allowed_origins="*")

DB_FILE = "chatbox.db"


def get_db():
    conn = sqlite3.connect(DB_FILE)
    conn.row_factory = sqlite3.Row
    return conn


def init_db():
    conn = get_db()
    conn.execute("""
        CREATE TABLE IF NOT EXISTS users (
            username TEXT PRIMARY KEY,
            password_hash TEXT NOT NULL
        )
    """)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS friendships (
            user_a TEXT NOT NULL,
            user_b TEXT NOT NULL,
            status TEXT NOT NULL,
            requested_by TEXT NOT NULL,
            PRIMARY KEY (user_a, user_b)
        )
    """)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS chat_messages (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            room TEXT NOT NULL,
            sender TEXT NOT NULL,
            content TEXT NOT NULL,
            created_at TEXT NOT NULL
        )
    """)
    conn.commit()
    conn.close()


init_db()


def friend_pair(user1, user2):
    """Always returns the two usernames in the same order, so we
    only ever store one row per friendship no matter who added whom."""
    return tuple(sorted([user1, user2]))


def friend_room(user1, user2):
    return "friend-" + "-".join(sorted([user1, user2]))


def login_required(f):
    @wraps(f)
    def wrapper(*args, **kwargs):
        if "username" not in session:
            return redirect(url_for("login"))
        return f(*args, **kwargs)
    return wrapper

# ---------------------------------------------------------------
# "Database" (just a Python list, in memory)
# ---------------------------------------------------------------
messages = []

# Tracks who is currently in each call room: { "room-code": [sid1, sid2] }
rooms = {}


def add_to_room(room, sid):
    members = rooms.setdefault(room, [])
    if sid not in members:
        members.append(sid)
    return members


def remove_from_room(room, sid):
    if room in rooms and sid in rooms[room]:
        rooms[room].remove(sid)
        if not rooms[room]:
            del rooms[room]


# ---------------------------------------------------------------
# Shared styling, written as a Python string
# ---------------------------------------------------------------
CSS = """
* { margin: 0; padding: 0; box-sizing: border-box; }
body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    background: #f7f7f9;
    color: #222;
    line-height: 1.6;
}
.navbar {
    display: flex;
    justify-content: space-between;
    align-items: center;
    background: #1f2933;
    padding: 1rem 2rem;
}
.logo { color: #fff; font-weight: 700; font-size: 1.3rem; }
.nav-links { list-style: none; display: flex; gap: 1.5rem; }
.nav-links a { color: #cbd2d9; text-decoration: none; font-weight: 500; }
.nav-links a:hover { color: #fff; }
.container { max-width: 900px; margin: 0 auto; padding: 2.5rem 1.5rem; min-height: 70vh; }
.hero { text-align: center; padding: 3rem 1rem; }
.hero h1 { font-size: 2.3rem; margin-bottom: 1rem; }
.hero p { color: #52606d; margin-bottom: 1.5rem; }
.btn {
    display: inline-block; background: #2563eb; color: #fff;
    padding: 0.7rem 1.5rem; border: none; border-radius: 6px;
    text-decoration: none; font-weight: 600; cursor: pointer; font-size: 1rem;
}
.btn:hover { background: #1d4ed8; }
.btn-danger { background: #dc2626; }
.btn-danger:hover { background: #b91c1c; }
.features { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1.5rem; margin-top: 2rem; }
.feature-card { background: #fff; padding: 1.5rem; border-radius: 10px; box-shadow: 0 1px 4px rgba(0,0,0,0.08); }
.feature-card h3 { margin-bottom: 0.5rem; color: #2563eb; }
.content-block { background: #fff; padding: 1.5rem; border-radius: 10px; box-shadow: 0 1px 4px rgba(0,0,0,0.08); margin-bottom: 1.5rem; }
.contact-form { background: #fff; padding: 2rem; border-radius: 10px; box-shadow: 0 1px 4px rgba(0,0,0,0.08); max-width: 500px; }
.contact-form label { display: block; margin-top: 1rem; margin-bottom: 0.3rem; font-weight: 600; }
.contact-form input, .contact-form textarea {
    width: 100%; padding: 0.6rem; border: 1px solid #cbd2d9; border-radius: 6px;
    font-size: 1rem; font-family: inherit;
}
.contact-form button { margin-top: 1.5rem; }
.flash { padding: 0.8rem 1rem; border-radius: 6px; margin-bottom: 1rem; font-weight: 500; }
.flash-success { background: #d1fae5; color: #065f46; }
.flash-error { background: #fee2e2; color: #991b1b; }
footer { text-align: center; padding: 1.5rem; color: #52606d; font-size: 0.9rem; }
.call-box { background: #fff; padding: 2rem; border-radius: 10px; box-shadow: 0 1px 4px rgba(0,0,0,0.08); max-width: 500px; }
.call-box input {
    width: 100%; padding: 0.6rem; border: 1px solid #cbd2d9; border-radius: 6px;
    font-size: 1rem; margin-bottom: 1rem;
}
#status { margin-top: 1rem; color: #52606d; font-weight: 500; }
"""


# ---------------------------------------------------------------
# Layout function — every page is built by passing content into this
# ---------------------------------------------------------------
def layout(title: str, body: str, flash: str = "") -> str:
    if "username" in session:
        auth_links = f"""
                <li><a href="/friends">Friends</a></li>
                <li><a href="/logout">Log Out ({session['username']})</a></li>
        """
    else:
        auth_links = """
                <li><a href="/login">Log In</a></li>
                <li><a href="/signup">Sign Up</a></li>
        """

    return f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} | Chat Box 2.0</title>
    <style>{CSS}</style>
</head>
<body>
    <header>
        <nav class="navbar">
            <div class="logo">Chat Box 2.0</div>
            <ul class="nav-links">
                <li><a href="/">Home</a></li>
                <li><a href="/about">About</a></li>
                <li><a href="/contact">Contact</a></li>
                <li><a href="/call">Call</a></li>
                <li><a href="/video-call">Video Call</a></li>
                {auth_links}
            </ul>
        </nav>
    </header>
    <main class="container">
        {flash}
        {body}
    </main>
    <footer>
        <p>&copy; 2026 Chat Box 2.0. Built entirely in Python.</p>
    </footer>
</body>
</html>
"""


# ---------------------------------------------------------------
# Pages — each one is just a Python function returning HTML
# ---------------------------------------------------------------
@app.route("/")
def home():
    body = """
    <section class="hero">
        <h1>Welcome to My Python Website</h1>
        <p>Every page here — HTML, CSS, and logic — is generated by Python code.</p>
        <a href="/contact" class="btn">Get in Touch</a>
    </section>
    <section class="features">
        <div class="feature-card"><h3>Pure Python</h3><p>No separate template files — everything lives in one .py script.</p></div>
        <div class="feature-card"><h3>Simple</h3><p>Just Flask and plain Python strings and functions.</p></div>
        <div class="feature-card"><h3>Extendable</h3><p>Add a new page by adding a new function and route.</p></div>
    </section>
    """
    return layout("Home", body)


@app.route("/about")
def about():
    body = """
    <section class="content-block">
        <h1>About This Site</h1>
        <p>
            This website is written completely in Python. There are no .html
            or .css files anywhere — every page is a Python function that
            returns a string of HTML, and all the styling is a single Python
            string too.
        </p>
        <p>
            Add a new page by writing a new function, decorating it with
            <code>@app.route(...)</code>, and returning HTML built from
            <code>layout(...)</code>.
        </p>
    </section>
    """
    return layout("About", body)


@app.route("/contact", methods=["GET", "POST"])
def contact():
    flash_html = ""

    if request.method == "POST":
        name = request.form.get("name", "").strip()
        email = request.form.get("email", "").strip()
        message = request.form.get("message", "").strip()

        if not name or not email or not message:
            flash_html = '<div class="flash flash-error">Please fill out all fields.</div>'
        else:
            messages.append({"name": name, "email": email, "message": message})
            return redirect(url_for("contact", sent=1))

    if request.args.get("sent"):
        flash_html = '<div class="flash flash-success">Thanks! Your message has been received.</div>'

    messages_html = ""
    if messages:
        items = "".join(
            f"<li><strong>{m['name']}</strong> ({m['email']}): {m['message']}</li>"
            for m in messages
        )
        messages_html = f"""
        <section class="content-block">
            <h2>Messages Received (demo)</h2>
            <ul>{items}</ul>
        </section>
        """

    body = f"""
    <section class="content-block">
        <h1>Contact Us</h1>
    </section>
    <section class="contact-form">
        <form method="POST" action="/contact">
            <label for="name">Name</label>
            <input type="text" id="name" name="name" placeholder="Your name">

            <label for="email">Email</label>
            <input type="email" id="email" name="email" placeholder="you@example.com">

            <label for="message">Message</label>
            <textarea id="message" name="message" rows="5" placeholder="Your message"></textarea>

            <button type="submit" class="btn">Send Message</button>
        </form>
    </section>
    {messages_html}
    """
    return layout("Contact", body, flash=flash_html)


@app.route("/signup", methods=["GET", "POST"])
def signup():
    error = ""
    if request.method == "POST":
        username = request.form.get("username", "").strip().lower()
        password = request.form.get("password", "")

        if not username or not password:
            error = "Please fill out both fields."
        elif len(username) < 3:
            error = "Username must be at least 3 characters."
        elif not username.replace("_", "").isalnum():
            error = "Username can only contain letters, numbers, and underscores."
        elif len(password) < 4:
            error = "Password must be at least 4 characters."
        else:
            conn = get_db()
            existing = conn.execute(
                "SELECT username FROM users WHERE username = ?", (username,)
            ).fetchone()
            if existing:
                error = "That ID is already taken. Try another."
                conn.close()
            else:
                conn.execute(
                    "INSERT INTO users (username, password_hash) VALUES (?, ?)",
                    (username, generate_password_hash(password)),
                )
                conn.commit()
                conn.close()
                session["username"] = username
                return redirect(url_for("friends"))

    error_html = f'<div class="flash flash-error">{html_lib.escape(error)}</div>' if error else ""

    body = f"""
    <section class="content-block" style="max-width:420px;">
        <h1>Create Your ID</h1>
        {error_html}
        <form method="POST" action="/signup">
            <label for="username">Username</label>
            <input type="text" id="username" name="username" placeholder="Pick a unique ID">

            <label for="password">Password</label>
            <input type="password" id="password" name="password" placeholder="Choose a password">

            <button type="submit" class="btn">Create Account</button>
        </form>
        <p style="margin-top:1rem;">Already have an account? <a href="/login">Log in</a></p>
    </section>
    """
    return layout("Sign Up", body)


@app.route("/login", methods=["GET", "POST"])
def login():
    error = ""
    if request.method == "POST":
        username = request.form.get("username", "").strip().lower()
        password = request.form.get("password", "")

        conn = get_db()
        user = conn.execute(
            "SELECT * FROM users WHERE username = ?", (username,)
        ).fetchone()
        conn.close()

        if user and check_password_hash(user["password_hash"], password):
            session["username"] = username
            return redirect(url_for("friends"))
        else:
            error = "Incorrect ID or password."

    error_html = f'<div class="flash flash-error">{html_lib.escape(error)}</div>' if error else ""

    body = f"""
    <section class="content-block" style="max-width:420px;">
        <h1>Log In</h1>
        {error_html}
        <form method="POST" action="/login">
            <label for="username">Username</label>
            <input type="text" id="username" name="username">

            <label for="password">Password</label>
            <input type="password" id="password" name="password">

            <button type="submit" class="btn">Log In</button>
        </form>
        <p style="margin-top:1rem;">No account yet? <a href="/signup">Create one</a></p>
    </section>
    """
    return layout("Log In", body)


@app.route("/logout")
def logout():
    session.pop("username", None)
    return redirect(url_for("home"))


@app.route("/friends", methods=["GET", "POST"])
@login_required
def friends():
    me = session["username"]
    conn = get_db()
    notice = ""
    notice_is_error = False

    if request.method == "POST":
        target = request.form.get("friend_username", "").strip().lower()
        if not target:
            notice = "Please enter a username."
            notice_is_error = True
        elif target == me:
            notice = "You can't add yourself."
            notice_is_error = True
        else:
            exists = conn.execute(
                "SELECT username FROM users WHERE username = ?", (target,)
            ).fetchone()
            if not exists:
                notice = f'No user found with the ID "{target}".'
                notice_is_error = True
            else:
                a, b = friend_pair(me, target)
                existing = conn.execute(
                    "SELECT * FROM friendships WHERE user_a = ? AND user_b = ?", (a, b)
                ).fetchone()
                if existing:
                    notice = "You're already friends, or a request is already pending."
                    notice_is_error = True
                else:
                    conn.execute(
                        "INSERT INTO friendships (user_a, user_b, status, requested_by) "
                        "VALUES (?, ?, 'pending', ?)",
                        (a, b, me),
                    )
                    conn.commit()
                    notice = f'Friend request sent to "{target}".'

    accepted_rows = conn.execute(
        "SELECT * FROM friendships WHERE (user_a = ? OR user_b = ?) AND status = 'accepted'",
        (me, me),
    ).fetchall()
    friend_list = [r["user_b"] if r["user_a"] == me else r["user_a"] for r in accepted_rows]

    incoming_rows = conn.execute(
        "SELECT * FROM friendships WHERE (user_a = ? OR user_b = ?) "
        "AND status = 'pending' AND requested_by != ?",
        (me, me, me),
    ).fetchall()
    incoming = [r["user_b"] if r["user_a"] == me else r["user_a"] for r in incoming_rows]

    outgoing_rows = conn.execute(
        "SELECT * FROM friendships WHERE (user_a = ? OR user_b = ?) "
        "AND status = 'pending' AND requested_by = ?",
        (me, me, me),
    ).fetchall()
    outgoing = [r["user_b"] if r["user_a"] == me else r["user_a"] for r in outgoing_rows]

    conn.close()

    def friend_row(name):
        safe = html_lib.escape(name)
        room = friend_room(me, name)
        return f"""
        <li class="content-block" style="display:flex; justify-content:space-between; align-items:center; flex-wrap:wrap; gap:0.5rem;">
            <strong>{safe}</strong>
            <span>
                <a href="/chat/{safe}" class="btn">Chat</a>
                <a href="/call?room={room}" class="btn">Call</a>
                <a href="/video-call?room={room}" class="btn">Video Call</a>
            </span>
        </li>
        """

    def incoming_row(name):
        safe = html_lib.escape(name)
        return f"""
        <li class="content-block" style="display:flex; justify-content:space-between; align-items:center;">
            <strong>{safe}</strong>
            <span>
                <form method="POST" action="/friends/accept/{safe}" style="display:inline;">
                    <button type="submit" class="btn">Accept</button>
                </form>
                <form method="POST" action="/friends/decline/{safe}" style="display:inline;">
                    <button type="submit" class="btn btn-danger">Decline</button>
                </form>
            </span>
        </li>
        """

    friend_items = "".join(friend_row(f) for f in friend_list) or "<p>No friends yet, add one below.</p>"
    incoming_items = "".join(incoming_row(f) for f in incoming) or "<p>No incoming requests.</p>"
    outgoing_items = (
        "".join(f"<li>{html_lib.escape(f)} (waiting for them to accept)</li>" for f in outgoing)
        or "<p>None right now.</p>"
    )

    notice_class = "flash-error" if notice_is_error else "flash-success"
    notice_html = f'<div class="flash {notice_class}">{html_lib.escape(notice)}</div>' if notice else ""

    body = f"""
    <section class="content-block">
        <h1>My ID: {html_lib.escape(me)}</h1>
        <p>Share this ID with friends so they can add you.</p>
    </section>

    <section class="content-block">
        <h2>Add a Friend</h2>
        {notice_html}
        <form method="POST" action="/friends">
            <input type="text" name="friend_username" placeholder="Friend's ID">
            <button type="submit" class="btn">Send Request</button>
        </form>
    </section>

    <section class="content-block">
        <h2>Incoming Requests</h2>
        <ul style="list-style:none; padding:0;">{incoming_items}</ul>
    </section>

    <section class="content-block">
        <h2>Sent Requests</h2>
        <ul>{outgoing_items}</ul>
    </section>

    <section>
        <h2>My Friends</h2>
        <ul style="list-style:none; padding:0;">{friend_items}</ul>
    </section>
    """
    return layout("Friends", body)


@app.route("/friends/accept/<friend_username>", methods=["POST"])
@login_required
def accept_friend(friend_username):
    me = session["username"]
    friend_username = friend_username.strip().lower()
    a, b = friend_pair(me, friend_username)
    conn = get_db()
    conn.execute(
        "UPDATE friendships SET status = 'accepted' WHERE user_a = ? AND user_b = ?",
        (a, b),
    )
    conn.commit()
    conn.close()
    return redirect(url_for("friends"))


@app.route("/friends/decline/<friend_username>", methods=["POST"])
@login_required
def decline_friend(friend_username):
    me = session["username"]
    friend_username = friend_username.strip().lower()
    a, b = friend_pair(me, friend_username)
    conn = get_db()
    conn.execute("DELETE FROM friendships WHERE user_a = ? AND user_b = ?", (a, b))
    conn.commit()
    conn.close()
    return redirect(url_for("friends"))


@app.route("/chat/<friend_username>")
@login_required
def chat_with(friend_username):
    me = session["username"]
    friend_username = friend_username.strip().lower()
    a, b = friend_pair(me, friend_username)

    conn = get_db()
    friendship = conn.execute(
        "SELECT * FROM friendships WHERE user_a = ? AND user_b = ? AND status = 'accepted'",
        (a, b),
    ).fetchone()
    if not friendship:
        conn.close()
        return redirect(url_for("friends"))

    room = friend_room(me, friend_username)
    history_rows = conn.execute(
        "SELECT sender, content FROM chat_messages WHERE room = ? ORDER BY id ASC",
        (room,),
    ).fetchall()
    conn.close()

    history_html = "".join(
        f'<div style="margin-bottom:0.5rem;"><strong>{html_lib.escape(r["sender"])}:</strong> '
        f'{html_lib.escape(r["content"])}</div>'
        for r in history_rows
    ) or "<p style='color:#52606d;'>No messages yet, say hi!</p>"

    safe_me = html_lib.escape(me)
    safe_friend = html_lib.escape(friend_username)

    body = f"""
    <section class="content-block">
        <h1>Chat with {safe_friend}</h1>
    </section>
    <section class="content-block" id="chatWindow" style="height:320px; overflow-y:auto;">
        {history_html}
    </section>
    <section class="contact-form" style="display:flex; gap:0.5rem; max-width:100%; align-items:flex-start;">
        <input type="text" id="msgInput" placeholder="Type a message..." style="flex:1; margin-bottom:0;">
        <button class="btn" id="sendBtn">Send</button>
    </section>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.7.5/socket.io.min.js"></script>
    <script>
        const socket = io();
        const room = "{room}";
        const me = "{safe_me}";
        const chatWindow = document.getElementById('chatWindow');
        const msgInput = document.getElementById('msgInput');
        const sendBtn = document.getElementById('sendBtn');

        socket.emit('join_chat', {{ room: room }});

        function escapeHtml(text) {{
            const div = document.createElement('div');
            div.textContent = text;
            return div.innerHTML;
        }}

        function addMessage(sender, content) {{
            const div = document.createElement('div');
            div.style.marginBottom = '0.5rem';
            div.innerHTML = '<strong>' + escapeHtml(sender) + ':</strong> ' + escapeHtml(content);
            chatWindow.appendChild(div);
            chatWindow.scrollTop = chatWindow.scrollHeight;
        }}

        sendBtn.onclick = () => {{
            const text = msgInput.value.trim();
            if (!text) return;
            socket.emit('chat_message', {{ room: room, sender: me, content: text }});
            msgInput.value = '';
        }};

        msgInput.addEventListener('keydown', (e) => {{
            if (e.key === 'Enter') sendBtn.click();
        }});

        socket.on('chat_message', (data) => {{
            addMessage(data.sender, data.content);
        }});

        chatWindow.scrollTop = chatWindow.scrollHeight;
    </script>
    """
    return layout(f"Chat with {friend_username}", body)


@app.route("/call")
def call():
    prefill = html_lib.escape(request.args.get("room", ""))
    body = """
    <section class="content-block">
        <h1>Voice Call</h1>
        <p>Open this page in two different browser windows (or send the link to
           someone else). Type the <strong>same room code</strong> in both, click
           <strong>Join Call</strong> on each, and allow microphone access when asked.</p>
    </section>

    <section class="call-box">
        <input type="text" id="roomInput" placeholder="Room code, e.g. hello123" value="__ROOM_PREFILL__">
        <button class="btn" id="joinBtn">Join Call</button>
        <button class="btn" id="muteBtn" style="display:none;">Mute</button>
        <button class="btn btn-danger" id="hangupBtn" style="display:none;">Hang Up</button>
        <p id="status">Not connected.</p>
        <audio id="remoteAudio" autoplay></audio>
    </section>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.7.5/socket.io.min.js"></script>
    <script>
        const socket = io();
        const statusEl = document.getElementById('status');
        const joinBtn = document.getElementById('joinBtn');
        const muteBtn = document.getElementById('muteBtn');
        const hangupBtn = document.getElementById('hangupBtn');
        const roomInput = document.getElementById('roomInput');
        const remoteAudio = document.getElementById('remoteAudio');

        let localStream = null;
        let peerConnection = null;
        let room = null;
        let isMuted = false;

        const rtcConfig = {
            iceServers: [{ urls: 'stun:stun.l.google.com:19302' }]
        };

        function createPeerConnection() {
            peerConnection = new RTCPeerConnection(rtcConfig);

            localStream.getTracks().forEach(track => {
                peerConnection.addTrack(track, localStream);
            });

            peerConnection.ontrack = (event) => {
                remoteAudio.srcObject = event.streams[0];
                statusEl.textContent = 'Connected! You should hear the other person now.';
            };

            peerConnection.onicecandidate = (event) => {
                if (event.candidate) {
                    socket.emit('ice-candidate', { room: room, candidate: event.candidate });
                }
            };
        }

        async function makeOffer() {
            const offer = await peerConnection.createOffer();
            await peerConnection.setLocalDescription(offer);
            socket.emit('offer', { room: room, sdp: offer });
        }

        joinBtn.onclick = async () => {
            room = 'voice-' + roomInput.value.trim();
            if (roomInput.value.trim() === '') {
                alert('Please enter a room code.');
                return;
            }

            try {
                localStream = await navigator.mediaDevices.getUserMedia({ audio: true, video: false });
            } catch (err) {
                statusEl.textContent = 'Could not access your microphone. Please allow microphone access and try again.';
                return;
            }

            socket.emit('join', { room: room });
            joinBtn.style.display = 'none';
            muteBtn.style.display = 'inline-block';
            hangupBtn.style.display = 'inline-block';
            roomInput.disabled = true;
            statusEl.textContent = 'Joining room...';
        };

        muteBtn.onclick = () => {
            isMuted = !isMuted;
            localStream.getAudioTracks().forEach(track => {
                track.enabled = !isMuted;
            });
            muteBtn.textContent = isMuted ? 'Unmute' : 'Mute';
        };

        hangupBtn.onclick = () => {
            socket.emit('leave', { room: room });
            endCall('Call ended.');
        };

        function endCall(message) {
            if (peerConnection) {
                peerConnection.close();
                peerConnection = null;
            }
            if (localStream) {
                localStream.getTracks().forEach(t => t.stop());
                localStream = null;
            }
            joinBtn.style.display = 'inline-block';
            muteBtn.style.display = 'none';
            hangupBtn.style.display = 'none';
            roomInput.disabled = false;
            isMuted = false;
            muteBtn.textContent = 'Mute';
            statusEl.textContent = message;
        }

        socket.on('status', (data) => {
            statusEl.textContent = data.msg;
        });

        socket.on('ready', async (data) => {
            statusEl.textContent = 'Peer found! Connecting...';
            createPeerConnection();
            if (data.initiator) {
                await makeOffer();
            }
        });

        socket.on('offer', async (data) => {
            if (!peerConnection) createPeerConnection();
            await peerConnection.setRemoteDescription(new RTCSessionDescription(data.sdp));
            const answer = await peerConnection.createAnswer();
            await peerConnection.setLocalDescription(answer);
            socket.emit('answer', { room: room, sdp: answer });
        });

        socket.on('answer', async (data) => {
            await peerConnection.setRemoteDescription(new RTCSessionDescription(data.sdp));
        });

        socket.on('ice-candidate', async (data) => {
            try {
                await peerConnection.addIceCandidate(new RTCIceCandidate(data.candidate));
            } catch (err) {
                console.error('Error adding ICE candidate', err);
            }
        });

        socket.on('peer-left', () => {
            endCall('The other person left the call.');
        });
    </script>
    """
    body = body.replace("__ROOM_PREFILL__", prefill)
    return layout("Call", body)


@app.route("/video-call")
def video_call():
    prefill = html_lib.escape(request.args.get("room", ""))
    body = """
    <section class="content-block">
        <h1>Video Call</h1>
        <p>Open this page in two different browser windows (or send the link to
           someone else). Type the <strong>same room code</strong> in both, click
           <strong>Join Call</strong> on each, and allow camera/microphone access
           when asked. Screen sharing can be turned on anytime during the call.</p>
    </section>

    <section class="call-box" style="max-width: 700px;">
        <input type="text" id="roomInput" placeholder="Room code, e.g. hello123" value="__ROOM_PREFILL__">
        <button class="btn" id="joinBtn">Join Call</button>
        <button class="btn" id="muteBtn" style="display:none;">Mute</button>
        <button class="btn" id="cameraBtn" style="display:none;">Disable Camera</button>
        <button class="btn" id="screenBtn" style="display:none;">Share Screen</button>
        <button class="btn btn-danger" id="hangupBtn" style="display:none;">Hang Up</button>
        <p id="status">Not connected.</p>

        <div style="display:flex; gap:1rem; margin-top:1rem; flex-wrap:wrap;">
            <div>
                <p style="font-size:0.85rem; color:#52606d; margin-bottom:0.3rem;">You</p>
                <video id="localVideo" autoplay muted playsinline
                       style="width:260px; height:180px; background:#111; border-radius:8px;"></video>
            </div>
            <div>
                <p style="font-size:0.85rem; color:#52606d; margin-bottom:0.3rem;">Other person</p>
                <video id="remoteVideo" autoplay playsinline
                       style="width:260px; height:180px; background:#111; border-radius:8px;"></video>
            </div>
        </div>
    </section>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.7.5/socket.io.min.js"></script>
    <script>
        const socket = io();
        const statusEl = document.getElementById('status');
        const joinBtn = document.getElementById('joinBtn');
        const muteBtn = document.getElementById('muteBtn');
        const cameraBtn = document.getElementById('cameraBtn');
        const screenBtn = document.getElementById('screenBtn');
        const hangupBtn = document.getElementById('hangupBtn');
        const roomInput = document.getElementById('roomInput');
        const localVideo = document.getElementById('localVideo');
        const remoteVideo = document.getElementById('remoteVideo');

        // Fallback: if autoplay still gets blocked, tapping the video retries it.
        remoteVideo.addEventListener('click', () => {
            if (remoteVideo.paused) {
                remoteVideo.muted = false;
                remoteVideo.play().catch(() => {});
            }
        });

        let localStream = null;
        let peerConnection = null;
        let room = null;
        let isMuted = false;
        let cameraOn = true;
        let screenSharing = false;
        let cameraTrack = null;
        let screenTrack = null;

        const rtcConfig = {
            iceServers: [{ urls: 'stun:stun.l.google.com:19302' }]
        };

        function createPeerConnection() {
            peerConnection = new RTCPeerConnection(rtcConfig);

            localStream.getTracks().forEach(track => {
                peerConnection.addTrack(track, localStream);
            });

            peerConnection.ontrack = (event) => {
                remoteVideo.srcObject = event.streams[0];
                // Some mobile browsers block autoplay of video with sound.
                // Starting muted (which is always allowed) then unmuting
                // right after works around that.
                remoteVideo.muted = true;
                remoteVideo.play().then(() => {
                    remoteVideo.muted = false;
                }).catch(err => {
                    console.warn('Autoplay was blocked, tap the video to start it', err);
                });
                statusEl.textContent = 'Connected!';
            };

            peerConnection.onicecandidate = (event) => {
                if (event.candidate) {
                    socket.emit('ice-candidate', { room: room, candidate: event.candidate });
                }
            };

            peerConnection.onnegotiationneeded = async () => {
                try {
                    const offer = await peerConnection.createOffer();
                    await peerConnection.setLocalDescription(offer);
                    socket.emit('offer', { room: room, sdp: offer });
                } catch (err) {
                    console.error('Renegotiation error', err);
                }
            };
        }

        async function makeOffer() {
            const offer = await peerConnection.createOffer();
            await peerConnection.setLocalDescription(offer);
            socket.emit('offer', { room: room, sdp: offer });
        }

        joinBtn.onclick = async () => {
            const code = roomInput.value.trim();
            if (!code) {
                alert('Please enter a room code.');
                return;
            }
            room = 'video-' + code;

            try {
                localStream = await navigator.mediaDevices.getUserMedia({ audio: true, video: true });
            } catch (err) {
                statusEl.textContent = 'Could not access your camera/microphone. Please allow access and try again.';
                return;
            }

            cameraTrack = localStream.getVideoTracks()[0];
            localVideo.srcObject = localStream;
            cameraOn = true;

            socket.emit('join', { room: room });
            joinBtn.style.display = 'none';
            muteBtn.style.display = 'inline-block';
            cameraBtn.style.display = 'inline-block';
            screenBtn.style.display = 'inline-block';
            hangupBtn.style.display = 'inline-block';
            roomInput.disabled = true;
            statusEl.textContent = 'Joining room...';
        };

        muteBtn.onclick = () => {
            isMuted = !isMuted;
            localStream.getAudioTracks().forEach(track => {
                track.enabled = !isMuted;
            });
            muteBtn.textContent = isMuted ? 'Unmute' : 'Mute';
        };

        cameraBtn.onclick = () => {
            if (!cameraTrack) return;
            cameraOn = !cameraOn;
            cameraTrack.enabled = cameraOn;
            cameraBtn.textContent = cameraOn ? 'Disable Camera' : 'Enable Camera';
        };

        screenBtn.onclick = async () => {
            if (!screenSharing) {
                let displayStream;
                try {
                    displayStream = await navigator.mediaDevices.getDisplayMedia({ video: true });
                } catch (err) {
                    return;
                }
                screenTrack = displayStream.getVideoTracks()[0];

                if (peerConnection) {
                    const videoSender = peerConnection.getSenders().find(s => s.track && s.track.kind === 'video');
                    if (videoSender) {
                        await videoSender.replaceTrack(screenTrack);
                    }
                }
                localVideo.srcObject = new MediaStream([screenTrack]);

                screenTrack.onended = () => {
                    stopScreenShare();
                };

                screenSharing = true;
                screenBtn.textContent = 'Stop Sharing';
                cameraBtn.disabled = true;
            } else {
                stopScreenShare();
            }
        };

        async function stopScreenShare() {
            if (screenTrack) {
                screenTrack.stop();
                screenTrack = null;
            }
            if (peerConnection && cameraTrack) {
                const videoSender = peerConnection.getSenders().find(s => s.track && s.track.kind === 'video');
                if (videoSender) {
                    await videoSender.replaceTrack(cameraTrack);
                }
            }
            localVideo.srcObject = localStream;
            screenSharing = false;
            screenBtn.textContent = 'Share Screen';
            cameraBtn.disabled = false;
        }

        hangupBtn.onclick = () => {
            socket.emit('leave', { room: room });
            endCall('Call ended.');
        };

        function endCall(message) {
            if (peerConnection) {
                peerConnection.close();
                peerConnection = null;
            }
            if (localStream) {
                localStream.getTracks().forEach(t => t.stop());
                localStream = null;
            }
            if (screenTrack) {
                screenTrack.stop();
                screenTrack = null;
            }
            cameraTrack = null;
            localVideo.srcObject = null;
            remoteVideo.srcObject = null;

            joinBtn.style.display = 'inline-block';
            muteBtn.style.display = 'none';
            cameraBtn.style.display = 'none';
            screenBtn.style.display = 'none';
            hangupBtn.style.display = 'none';
            roomInput.disabled = false;
            isMuted = false;
            cameraOn = true;
            screenSharing = false;
            muteBtn.textContent = 'Mute';
            cameraBtn.textContent = 'Disable Camera';
            screenBtn.textContent = 'Share Screen';
            statusEl.textContent = message;
        }

        socket.on('status', (data) => {
            statusEl.textContent = data.msg;
        });

        socket.on('ready', async (data) => {
            statusEl.textContent = 'Peer found! Connecting...';
            createPeerConnection();
            if (data.initiator) {
                await makeOffer();
            }
        });

        socket.on('offer', async (data) => {
            if (!peerConnection) createPeerConnection();
            await peerConnection.setRemoteDescription(new RTCSessionDescription(data.sdp));
            const answer = await peerConnection.createAnswer();
            await peerConnection.setLocalDescription(answer);
            socket.emit('answer', { room: room, sdp: answer });
        });

        socket.on('answer', async (data) => {
            await peerConnection.setRemoteDescription(new RTCSessionDescription(data.sdp));
        });

        socket.on('ice-candidate', async (data) => {
            try {
                await peerConnection.addIceCandidate(new RTCIceCandidate(data.candidate));
            } catch (err) {
                console.error('Error adding ICE candidate', err);
            }
        });

        socket.on('peer-left', () => {
            endCall('The other person left the call.');
        });
    </script>
    """
    body = body.replace("__ROOM_PREFILL__", prefill)
    return layout("Video Call", body)



# ---------------------------------------------------------------
# Chat messaging events — 1:1 text chat between friends
# ---------------------------------------------------------------
@socketio.on("join_chat")
def on_join_chat(data):
    room = (data or {}).get("room", "")
    if room:
        join_room(room)


@socketio.on("chat_message")
def on_chat_message(data):
    room = (data or {}).get("room", "")
    sender = (data or {}).get("sender", "")
    content = (data or {}).get("content", "").strip()
    if not room or not sender or not content:
        return

    conn = get_db()
    conn.execute(
        "INSERT INTO chat_messages (room, sender, content, created_at) VALUES (?, ?, ?, datetime('now'))",
        (room, sender, content),
    )
    conn.commit()
    conn.close()

    emit("chat_message", {"sender": sender, "content": content}, room=room)


# ---------------------------------------------------------------
# Signaling events — these just introduce the two browsers to each
# other so they can set up a direct WebRTC audio connection.
# ---------------------------------------------------------------
@socketio.on("join")
def on_join(data):
    room = (data or {}).get("room", "").strip()
    if not room:
        return

    join_room(room)
    members = add_to_room(room, request.sid)
    count = len(members)

    if count == 1:
        emit("status", {"msg": "Waiting for someone else to join..."})
    elif count == 2:
        caller_sid, callee_sid = members[0], members[1]
        emit("ready", {"initiator": True}, room=caller_sid)
        emit("ready", {"initiator": False}, room=callee_sid)
    else:
        emit("status", {"msg": "Room is full (2 people max). Try a different code."})
        leave_room(room)
        remove_from_room(room, request.sid)


@socketio.on("offer")
def on_offer(data):
    emit("offer", data, room=data["room"], include_self=False)


@socketio.on("answer")
def on_answer(data):
    emit("answer", data, room=data["room"], include_self=False)


@socketio.on("ice-candidate")
def on_ice_candidate(data):
    emit("ice-candidate", data, room=data["room"], include_self=False)


@socketio.on("leave")
def on_leave(data):
    room = (data or {}).get("room", "")
    if not room:
        return
    leave_room(room)
    remove_from_room(room, request.sid)
    emit("peer-left", {}, room=room)


@socketio.on("disconnect")
def on_disconnect():
    for room in list(rooms.keys()):
        if request.sid in rooms[room]:
            remove_from_room(room, request.sid)
            emit("peer-left", {}, room=room)


if __name__ == "__main__":
    socketio.run(app, debug=True, host='0.0.0.0', port=5000)